### ISSUE TITLE
После обновления системы до версии 4.4.2 перестали запускаться автотесты с ошибкой The field `attachments` in the JSON string is not defined in the `TestRunV2GetModel` properties

### ISSUE THREAD

**Issue by Vegeniy** [testit-tms/adapters-java#103]
Подскажите, как решить эту проблему. Активный гуглопоиск не помог.

java.lang.IllegalArgumentException: The field `attachments` in the JSON string is not defined in the `TestRunV2GetModel` properties. JSON: {"startedOn":null,"completedOn":null,"stateName":"NotStarted","projectId":"364acd90-94b1-419a-9d96-cfd2a4c2f9ea","testPlanId":null,"testResults":[],"createdDate":"2023-10-16T14:29:04.582Z","modifiedDate":"2023-10-16T14:29:04.582Z","createdById":"a66ad0f9-71a4-465d-9fd7-f84789807098","modifiedById":"a66ad0f9-71a4-465d-9fd7-f84789807098","createdByUserName":"UserName","attachments":[],"links":[],"id":"461bd185-d47c-4c60-96fe-dff7f06e21e6","name":"TestRun_2023-10-16T14:29:04","description":null,"launchSource":"Test IT"}
	at ru.testit.client.model.TestRunV2GetModel.validateJsonObject(TestRunV2GetModel.java:574)
	at ru.testit.client.model.TestRunV2GetModel$CustomTypeAdapterFactory$1.read(TestRunV2GetModel.java:648)
	at ru.testit.client.model.TestRunV2GetModel$CustomTypeAdapterFactory$1.read(TestRunV2GetModel.java:638)
	at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199)
	at com.google.gson.Gson.fromJson(Gson.java:963)
	at com.google.gson.Gson.fromJson(Gson.java:928)
	at com.google.gson.Gson.fromJson(Gson.java:877)
	at ru.testit.client.invoker.JSON.deserialize(JSON.java:357)
	at ru.testit.client.invoker.ApiClient.deserialize(ApiClient.java:845)
	at ru.testit.client.invoker.ApiClient.handleResponse(ApiClient.java:1055)
	at ru.testit.client.invoker.ApiClient.execute(ApiClient.java:979)
	at ru.testit.client.api.TestRunsApi.createEmptyWithHttpInfo(TestRunsApi.java:1381)
	at ru.testit.client.api.TestRunsApi.createEmpty(TestRunsApi.java:1358)
	at ru.testit.clients.TmsApiClient.createTestRun(TmsApiClient.java:58)
	at ru.testit.services.AdapterManager.startTests(AdapterManager.java:90)
	at ru.testit.listener.BaseTestNgListener.onStart(BaseTestNgListener.java:65)
	at org.testng.SuiteRunner.invokeListeners(SuiteRunner.java:213)
	at org.testng.SuiteRunner.run(SuiteRunner.java:274)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
	at org.testng.TestNG.runSuites(TestNG.java:1063)
	at org.testng.TestNG.run(TestNG.java:1031)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)

**Comment by Vegeniy** [comment]
Проблема решилась после апдейта зависимостей в POM файле с 1.3.5 до 1.4.0 или 1.4.1 (с версиями 1.3.6, 1.3.7, 1.3.8 и 2.1.0 по прежнему ловятся всякого рода ошибки )
