### ISSUE TITLE
Provider ru.testit.listener.Junit5PostDiscoveryFilter could not be instantiated при использовании testit-adapter-junit5

### ISSUE THREAD

**Issue by gadya83** [testit-tms/adapters-java#49]
Приветствую, коллеги!
Подключил библиотеку testit-adapter-junit5 к своему проекту, подключил аннотации, запуск тестов или билд стал падать с ошибкой. Создал проект полностью копипастом из Readme (pom, properties, test). В итоге при запуске тестов выходит та же ошибка:
[main] WARN ru.testit.properties.AppProperties - The configuration file specifies a private token. It is not safe. Use TMS_PRIVATE_TOKEN environment variable
Exception in thread "main" java.util.ServiceConfigurationError: org.junit.platform.launcher.PostDiscoveryFilter: Provider ru.testit.listener.Junit5PostDiscoveryFilter could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:232)
	at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at java.lang.Iterable.forEach(Iterable.java:74)
	at org.junit.platform.launcher.core.LauncherFactory.collectPostDiscoveryFilters(LauncherFactory.java:163)
	at org.junit.platform.launcher.core.LauncherFactory.createDefaultLauncher(LauncherFactory.java:132)
	at org.junit.platform.launcher.core.LauncherFactory.create(LauncherFactory.java:125)
	at org.junit.platform.launcher.core.LauncherFactory.create(LauncherFactory.java:109)
	at com.intellij.junit5.JUnit5IdeaTestRunner.createListeners(JUnit5IdeaTestRunner.java:48)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:31)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:221)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: java.lang.IllegalArgumentException: Invalid UUID string: 
	at java.util.UUID.fromString(UUID.java:194)
	at ru.testit.clients.TmsApiClient.getTestFromTestRun(TmsApiClient.java:96)
	at ru.testit.services.AdapterManager.getTestFromTestRun(AdapterManager.java:509)
	at ru.testit.listener.Junit5PostDiscoveryFilter.<init>(Junit5PostDiscoveryFilter.java:24)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
	... 11 more
Токен передавал всеми способами (в testit.properties, через TMS_PRIVATE_TOKEN, через tmsPrivateToken), результат не менялся. При этом с testit-adapter-junit4 все работает корректно.

**Comment by testit-tms** [comment]
Добрый день! Можете прислать тестовый проект, в котором возникает ошибка?

**Comment by ElUnicornio** [comment]
Такая же ситуация после того как обновил библиотеку testit-adapter-junit5 на версию 1.0.0

**Comment by AMGESHIK** [comment]
У меня тоже только на версии 1.0.0 такая проблема 👍

**Comment by ElUnicornio** [comment]
На версии 1.1.0 тоже самое. Но мне помогло переключение adapterMode на 2 в testit.properties файле. После обновы дефолтный 0 требует чтобы был указан run_id. Когда как 2 создает @testit-tms @AMGESHIK @gadya83

**Comment by AMGESHIK** [comment]
@ElUnicornio Спасибо, попробую

**Comment by testit-tms** [comment]
А вы смотрели режимы работы адаптера? https://github.com/testit-tms/adapters-java/tree/main/testit-adapter-junit5#configuration

Дефолтный режим - 0. Он для запуска тестов из ci/cd через вебкухи с уже готовым тест раном. Если вам просто пролить тесты, то надо использовать режим 2, в котором всегда создается новый тест ран.

**Comment by ElUnicornio** [comment]
До версии 1.0.0 режим 0 тоже создавал тест ран

**Comment by testit-tms** [comment]
да, там не было вообще режимов работы. Поэтому мы и обновили мажорную версию, так как ломается совместимость.

**Comment by gadya83** [comment]
Увы, проверить не могу. Фри версия давалась на 14 дней)
