### ISSUE TITLE
Injecting citrus context

### ISSUE THREAD

**Issue by L1nstat** [testit-tms/adapters-java#57]
Hi. 
In continuation https://github.com/testit-tms/adapters-java/issues/31.

Citrus tests means use the citrus context. It is injecting on method level by use TestNg annotation @parameters and writing to arguments, for example:
@parameters(value = {"testContext"})
public void example(@optional @CitrusResource TestContext testContext)

When i use it i get an error:
java.lang.NullPointerException
at ru.testit.listener.BaseTestNgListener.getParameters(BaseTestNgListener.java:153)
at ru.testit.listener.BaseTestNgListener.startTestCase(BaseTestNgListener.java:97)
at ru.testit.listener.BaseTestNgListener.onTestStart(BaseTestNgListener.java:87)
at org.testng.internal.TestListenerHelper.runTestListeners(TestListenerHelper.java:106)
at org.testng.internal.invokers.TestInvoker.runTestResultListener(TestInvoker.java:276)

So adapter doesn't see this param when getting params from test result.
Example project: https://github.com/L1nstat/CitrusTestExample.git

**Comment by testit-tms** [comment]
Try to use 1.1.1 version
